import {formatKST,COURSES,ARITHMETIC_MODES,ARITHMETIC_LENGTHS} from './core.mjs?v=20260911-arithmetic1';
// 모든 훈련의 최신순·분포도 UI. 응답이 늦게 도착해도 현재 탭을 덮어쓰지 않습니다.
export function createRankingExplorer({game,apiBase,filters,refresh}){
 const get=id=>document.getElementById(id),tabs=document.createElement('div');tabs.className='rank-tabs';tabs.setAttribute('role','group');tabs.setAttribute('aria-label','기록 보기');let view='rank',requestId=0;
 for(const [key,label] of [['rank','순위순'],['latest','최신순'],['distribution','전체 분포도']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.rankView=key;button.setAttribute('aria-pressed',key===view);button.onclick=()=>{view=key;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b===button));refresh();};tabs.append(button);}
 get('ranking').querySelector('h1').after(tabs);
 const make=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
 const metric=n=>game==='memory'?`${n}점`:`${(n/1000).toFixed(2)}초/문항`;
 const detail=r=>game==='subtraction'?`${COURSES[r.course]?.name||''} · ${r.step}씩 빼기`:game==='arithmetic'?`${ARITHMETIC_MODES[r.mode]} · ${ARITHMETIC_LENGTHS[r.length]}문제`:'';
 async function render(){const serial=++requestId;const searchBox=get('rankSearch')||get('rankNickname').closest('[role="search"]');if(searchBox)searchBox.hidden=view==='distribution';
 if(view==='rank')return false;
 const target=get('rankList'),params=new URLSearchParams({...filters(),game,view});if(view==='distribution')params.delete('nickname');
 get('rankNote').textContent=view==='latest'?'최근 등록된 기록을 최대 50건까지 보여드립니다.':'선택한 조건의 전체 등록 기록을 집계합니다.';
 target.textContent=apiBase?'기록을 불러오고 있습니다…':'미리보기에서는 전체 기록을 조회할 수 없습니다.';if(!apiBase)return true;
 const load=async extra=>{const query=new URLSearchParams(params);if(extra!==undefined)query.set('value',extra);const response=await fetch(apiBase+'/analytics?'+query,{signal:AbortSignal.timeout(10000)});const data=await response.json();if(!response.ok)throw new Error(data.error||'기록을 불러오지 못했습니다.');return data;};
 try{const data=await load();if(serial!==requestId)return true;target.replaceChildren();if(view==='latest'){if(!data.rows.length)target.textContent='등록된 기록이 없습니다.';for(const r of data.rows){const row=make('div',undefined,'row'),info=make('div'),value=make('div',undefined,'score');info.append(make('strong',r.nickname),make('small',detail(r)));value.append(make('strong',metric(r.metric)),make('small',formatKST(r.created)));row.append(info,value);target.append(row);}return true;}
 const box=make('div',undefined,'distribution');target.append(box);box.append(make('p',`등록 기록 ${data.count.toLocaleString('ko-KR')}건`,'note'));if(!data.count){box.append(make('p','아직 분포도를 그릴 기록이 없습니다.'));return true;}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 220');svg.setAttribute('role','img');svg.setAttribute('aria-label',`전체 ${data.count}건의 ${game==='memory'?'점수':'문항당 평균 시간'} 분포. 구간별 건수는 아래 표에서 확인할 수 있습니다.`);const max=Math.max(...data.bins.map(b=>b.count));const w=300/data.bins.length;
 data.bins.forEach((bin,i)=>{const height=145*bin.count/max,rect=document.createElementNS(ns,'rect');for(const [k,v] of Object.entries({x:40+i*w+2,y:170-height,width:Math.max(1,w-4),height,rx:3,fill:'#78953a'}))rect.setAttribute(k,String(v));const title=document.createElementNS(ns,'title');title.textContent=`${metric(bin.from)} ~ ${metric(bin.to)}: ${bin.count}건`;rect.append(title);svg.append(rect);});
 for(const [x,y,label,anchor] of [[40,20,`${max}건`,'start'],[40,192,metric(data.min),'start'],[340,192,metric(data.max),'end'],[190,216,game==='memory'?'점수 →':'평균 풀이 시간 →','middle']]){const text=document.createElementNS(ns,'text');text.setAttribute('x',x);text.setAttribute('y',y);text.setAttribute('text-anchor',anchor);text.setAttribute('font-size','11');text.setAttribute('fill','#52645b');text.textContent=label;svg.append(text);}box.append(svg);
 const tableDetails=make('details'),summary=make('summary','구간별 기록 수'),table=make('table');tableDetails.append(summary,table);data.bins.forEach((b,i)=>{const row=make('tr');row.append(make('th',`${metric(b.from)} ~ ${metric(b.to)}${i===data.bins.length-1?' 이하':' 미만'}`),make('td',`${b.count}건`));table.append(row);});box.append(tableDetails);
 const label=make('label',game==='memory'?'나의 점수':'나의 평균 풀이 시간 (초/문항)');label.htmlFor='percentileValue';const input=make('input');input.id='percentileValue';input.type='number';input.min=game==='memory'?'0':'0.001';input.step=game==='memory'?'1':'any';input.inputMode=game==='memory'?'numeric':'decimal';input.placeholder=game==='memory'?'예: 40':'예: 1.25';const button=make('button','확인','secondary');button.type='button';const controls=make('div',undefined,'compare'),out=make('output');out.setAttribute('aria-live','polite');controls.append(input,button);box.append(label,controls,out,make('p','백분위가 높을수록 좋은 기록입니다. 동률은 중간 순위로 계산합니다. 참여자 수가 아닌 등록 기록 기준입니다.','note'));
 let comparison=0;const compare=async()=>{const version=++comparison,value=Number(input.value);if(!input.value.trim()||!Number.isFinite(value)||value<0||game!=='memory'&&value===0||game==='memory'&&!Number.isInteger(value)){out.textContent='기록을 올바르게 입력해 주세요.';return;}button.disabled=true;out.textContent='계산 중…';try{const result=await load(String(game==='memory'?value:value*1000));if(serial===requestId&&version===comparison)out.textContent=result.percentile===null?'비교할 기록이 없습니다.':`백분위 ${result.percentile.toFixed(1)}%`;}catch(e){if(serial===requestId&&version===comparison)out.textContent=e.message;}finally{button.disabled=false;}};button.onclick=compare;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();compare();}};
 }catch(e){if(serial===requestId)target.textContent=e.message;}return true;
 }
 return {render,active:()=>view!=='rank',invalidate:()=>requestId++};
}
