import {memoryLayout,memoryRows,memoryBoardSize,validNickname,formatKST,bindPressInput} from './core.mjs?v=20260910-memory20';

const $=id=>document.getElementById(id);
const apiBase=(window.TRAINING_CONFIG?.apiBase||'').replace(/\/$/,'');
const storage={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch{}}};
let identity=storage.get('training.identity',null);if(typeof identity!=='string'||identity.length!==36)identity=crypto.randomUUID();storage.set('training.identity',identity);
async function api(path,body){const r=await fetch(apiBase+'/memory'+path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(10000)});const data=await r.json();if(!r.ok)throw new Error(data.error||'연결에 실패했습니다.');return data;}
let boardRows=0,boardColumns=0;
function fitBoard(){if(!['memorize','recall','review'].includes(phase)||!boardRows)return;const board=$('board'),parent=board.parentElement,style=window.getComputedStyle(parent),rect=board.getBoundingClientRect(),viewport=window.visualViewport;const width=parent.clientWidth-parseFloat(style.paddingLeft||0)-parseFloat(style.paddingRight||0);const bottom=(viewport?viewport.height+viewport.offsetTop:window.innerHeight)-16;const size=memoryBoardSize(width,Math.max(0,bottom-rect.top),boardColumns,boardRows);board.style.width=size.width+'px';board.style.height=size.height+'px';board.style.gap=size.gap+'px';board.style.gridTemplateRows='repeat('+boardRows+',minmax(0,'+size.tile+'px))';board.style.setProperty('--tile-font',size.font+'px');board.style.setProperty('--tile-radius',size.radius+'px');board.style.setProperty('--tile-border',Math.min(1,size.tile*.03)+'px');}
window.addEventListener('resize',fitBoard);window.visualViewport?.addEventListener('resize',fitBoard);
let active=null,recallStart=0,currentRound=null,rankRequest=0,search='';
let count=4,round=0,score=0,mistakes=0,expected=1,layout=[],phase='home',deadline=0,clock=null,peak=4;
function show(id){for(const name of ['home','play','result','ranking','records'])$(name).hidden=name!==id;}
async function start(){if($('start').disabled)return;$('start').disabled=true;$('again').disabled=true;$('homeStatus').textContent='';try{const remote=apiBase?await api('/start',{identity}):{seed:crypto.getRandomValues(new Uint32Array(1))[0]};active={...remote,rounds:[],verified:false,published:false};count=4;round=0;score=0;mistakes=0;peak=4;$('publishBox').hidden=true;$('resultRanking').hidden=true;$('saveStatus').textContent='';$('publishStatus').textContent='';$('consent').checked=false;$('publish').disabled=false;show('play');nextRound();}catch(e){home();$('homeStatus').textContent='시작하지 못했습니다. '+e.message;}finally{$('start').disabled=false;$('again').disabled=false;}}
function nextRound(){clearInterval(clock);round++;expected=1;phase='memorize';$('hint').classList.remove('urgent');peak=Math.max(peak,count);$('roundLabel').textContent=score+'점';$('phase').textContent='기억하세요';const rows=memoryRows(count),columns=Math.max(...rows);boardRows=rows.length;boardColumns=columns;layout=memoryLayout(count,active.seed,round);currentRound={clicks:[],endedAt:0};$('board').style.gridTemplateColumns='repeat('+(columns*2)+',minmax(0,1fr))';$('board').replaceChildren();layout.forEach((n,i)=>{const b=document.createElement('button');b.className='tile'+(n===null?' empty':'');b.textContent=n??'';let row=0,offset=i;while(offset>=rows[row])offset-=rows[row++];b.style.gridRow=String(row+1);b.style.gridColumn=(1+columns-rows[row]+offset*2)+' / span 2';b.disabled=true;b.dataset.cell=i;b.setAttribute('aria-label',n===null?'빈 칸':String(n));$('board').append(b);});fitBoard();deadline=performance.now()+2000;recallStart=deadline;tick();clock=setInterval(tick,40);}
function tick(){const now=performance.now();if(phase==='memorize'){const left=deadline-now;if(left>0){$('hint').textContent='';return;}phase='recall';deadline+=2000;$('phase').textContent='순서대로 누르세요';[...$('board').children].forEach((b,i)=>{b.textContent='';b.className='tile covered';b.disabled=false;b.setAttribute('aria-label','가려진 칸 '+(i+1));});}
if(phase==='recall'){const left=deadline-now;if(left<=0){endRound(false,true);return;}$('hint').textContent=(left/1000).toFixed(1)+'초';$('hint').classList.toggle('urgent',left<=1000);}
else if(phase==='review'){const left=deadline-now;if(left<=0){if($('quitDialog').open)$('quitDialog').close();hubExit=false;if(mistakes<3)nextRound();else{clearInterval(clock);phase='result';show('result');$('score').textContent=score;finishRun();}}else $('hint').textContent=Math.ceil(left/1000)+'초';}}
function choose(i){if(phase!=='recall'||$('quitDialog').open)return;if(performance.now()>=deadline){endRound(false,true);return;}const b=$('board').children[i];if(!b||b.disabled)return;const n=layout[i];currentRound.clicks.push({index:i,at:performance.now()-recallStart});if(n===expected){score++;$('roundLabel').textContent=score+'점';b.className='tile done';b.textContent=n;b.setAttribute('aria-label',n+' 정답');b.disabled=true;expected++;if(expected>count)endRound(true);else{deadline=performance.now()+2000;tick();}}else{b.className='tile missed';endRound(false);}}
function endRound(ok,timedOut=false){if(phase!=='recall')return;currentRound.endedAt=performance.now()-recallStart;active.rounds.push(currentRound);phase='review';$('hint').classList.remove('urgent');deadline=performance.now()+2000;if(!ok)mistakes++;$('roundLabel').textContent=score+'점';$('phase').textContent=ok?'정답':timedOut?'시간 초과':'오답';$('hint').textContent='';[...$('board').children].forEach((b,i)=>{b.disabled=true;if(layout[i]!==null){b.textContent=layout[i];b.setAttribute('aria-label',String(layout[i]));if(!ok&&layout[i]===expected)b.className='tile target';}});count=ok?count+1:Math.max(2,count-1);tick();}
bindPressInput($('board'),'[data-cell]',b=>choose(Number(b.dataset.cell)));
$('start').onclick=start;$('again').onclick=start;
function home(){clearInterval(clock);phase='home';show('home');}let hubExit=false;function leave(){hubExit=false;if(['memorize','recall','review'].includes(phase))$('quitDialog').showModal();else home();}$('quit').onclick=leave;$('brand').onclick=e=>{e.preventDefault();if(['memorize','recall','review'].includes(phase)){$('quitDialog').showModal();hubExit=true;}else location.href='./';};$('homeButton').onclick=home;$('keep').onclick=()=>{hubExit=false;$('quitDialog').close();};$('stop').onclick=()=>{$('quitDialog').close();home();if(hubExit)location.href='./';};document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});

async function finishRun(){const finished=active;finished.score=score;storage.set('training.memory.records',[{score,date:Date.now()},...memoryRecords()].slice(0,50));if(!apiBase){$('saveStatus').textContent='미리보기에서는 랭킹 등록을 사용할 수 없습니다.';return;}$('saveStatus').textContent='기록을 확인하고 있습니다…';try{const result=await api('/finish',{identity,token:finished.token,rounds:finished.rounds});if(result.score!==finished.score)throw new Error('점수를 확인하지 못했습니다.');finished.verified=true;if(active===finished&&phase==='result'){$('saveStatus').textContent='';$('publishBox').hidden=false;$('nickname').value=storage.get('training.nickname','');}}catch(e){if(active===finished&&phase==='result')$('saveStatus').textContent=e.message;}}
$('publish').onclick=async()=>{const finished=active;if(!finished?.verified||finished.published)return;const nickname=$('nickname').value.trim();if(!validNickname(nickname)){$('publishStatus').textContent='닉네임은 한글·영문·숫자·_로 2~12자 입력해 주세요.';return;}if(!$('consent').checked){$('publishStatus').textContent='기록 공개에 동의해 주세요.';return;}$('publish').disabled=true;try{await api('/publish',{identity,token:finished.token,nickname});finished.published=true;storage.set('training.nickname',nickname);if(active===finished){$('publishStatus').textContent='등록했습니다';$('resultRanking').hidden=false;}}catch(e){if(active===finished){$('publishStatus').textContent=e.message;$('publish').disabled=false;}}};
async function ranking(){phase='ranking';show('ranking');const serial=++rankRequest;$('rankNote').textContent=search?'검색 결과에도 전체 순위를 표시합니다.':'상위 50위까지만 조회할 수 있습니다';$('rankList').textContent=apiBase?'기록을 불러오고 있습니다…':'미리보기에서는 랭킹을 사용할 수 없습니다.';if(!apiBase)return;try{const {rows}=await api('/ranking?period='+$('rankPeriod').value+(search?'&nickname='+encodeURIComponent(search):''));if(serial!==rankRequest||phase!=='ranking')return;$('rankList').replaceChildren();if(!rows.length)$('rankList').textContent='등록된 기록이 없습니다.';for(const r of rows){const row=document.createElement('div');row.className='row';const info=document.createElement('div'),name=document.createElement('strong'),date=document.createElement('small'),points=document.createElement('strong');name.textContent=r.rank+'. '+r.nickname;date.textContent=formatKST(r.created);points.className='points';points.textContent=r.score+'점';info.append(name,date);row.append(info,points);$('rankList').append(row);}}catch(e){if(serial===rankRequest&&phase==='ranking')$('rankList').textContent=e.message;}}
$('showRanking').onclick=ranking;$('resultRanking').onclick=()=>{search='';$('rankNickname').value='';ranking();};$('rankBack').onclick=home;$('searchRanking').onclick=()=>{search=$('rankNickname').value.trim();ranking();};$('rankNickname').onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();$('searchRanking').click();}};$('clearSearch').onclick=()=>{search='';$('rankNickname').value='';ranking();};

$('rankPeriod').onchange=ranking;

function memoryRecords(){const rows=storage.get('training.memory.records',[]);return Array.isArray(rows)?rows.filter(r=>r&&Number.isInteger(r.score)&&Number.isFinite(r.date)).slice(0,50):[];}
function records(){phase='records';show('records');const list=$('recordList');list.replaceChildren();const rows=memoryRecords();if(!rows.length)list.textContent='아직 기록이 없습니다. 첫 훈련을 시작해 보세요.';for(const r of rows){const item=document.createElement('div');item.className='row';const detail=document.createElement('div'),name=document.createElement('strong'),date=document.createElement('small'),points=document.createElement('strong');name.textContent='순간 기억';date.textContent=formatKST(r.date);points.textContent=r.score+'점';detail.append(name,date);item.append(detail,points);list.append(item);}}
$('showRecords').onclick=records;$('recordBack').onclick=home;$('clearRecords').onclick=()=>{if(confirm('이 브라우저의 훈련 기록을 모두 삭제할까요? 전체 랭킹 기록은 유지됩니다.')){storage.set('training.memory.records',[]);records();}};
